### ISSUE TITLE
TrueColor OSD is not displaying chars

### ISSUE THREAD

**Issue by pbiering** [pbiering/vdr-plugin-reelbox#10]
it should work according to:

Sttng skin + true color works fine.

_Originally posted by @ua0lnj in https://github.com/pbiering/vdr-plugin-reelbox/issues/6#issuecomment-781691671_

**Comment by pbiering** [comment]
here it is not working having set
`reelbox.TRCLosd = 1`
have enabled a debug log line with https://github.com/pbiering/vdr-plugin-reelbox/commit/8584c12653794d61952cde70ebd64d2d07c36b51

can you please apply on your side and report whether the output looks like on my side:

```
reelbox: DEBUG DrawText DrawText: colorFg=ff000000 colorBg=ff00fcfc x=576 y=0 w=143 h=19 'Fr. 19.02. 08:01'
...
reelbox: DEBUG DrawText DrawText: colorFg=ff000000 colorBg=ff00fcfc x=0 y=38 w=712 h=19 ' 1 Programm'
reelbox: DEBUG DrawText DrawText: colorFg=fffcfcfc colorBg=7f000000 x=0 y=38 w=712 h=19 ' 1 Programm'
```
Thank you!

**Comment by ua0lnj** [comment]
I found it.
I use reelbox -nofb
So, no reelbox: DEBUG DrawText DrawText: in the log.

**Comment by pbiering** [comment]
confirmed, --nofb used -> TextColors are still ok.
Can you remember what the advantage is/was using OSD with framebuffer to eHD?

**Comment by ua0lnj** [comment]
I have always used - nofb, maybe because it's easier.

**Comment by pbiering** [comment]
after some debugging I found the reason...

there is a bunch of code not active which should draw text in case of Setup.Antialias=1

Currently enforced to "false" now in the code -> text is now displayed, but font is not really looking nice

https://github.com/pbiering/vdr-plugin-reelbox/commit/61b79cc2a990ab0262260b69dd6354c2a8bd05ea

Don't know whether it makes sense to put more efforts into...
