### ISSUE TITLE
osdteletext is silently closing

### ISSUE THREAD

**Issue by pbiering** [pbiering/vdr-plugin-reelbox#6]
osdteletext is silently closing instantly, nothing visible

**Comment by ua0lnj** [comment]
Everything works fine, if you set the width and height of the teletext menu, no more than the OSD size :)

**Comment by pbiering** [comment]
added some debug code and found
- OSD 256 color mode and osdteletext in 4 bit color mode (strange colors, but working)
- OSD true color mode and osdteletext in normal color mode -> but here LCARS is not showing any text, only surrounding boxes for unknown reason
- - OSD 256 color mode and osdteletext in normal mode mode -> no longer silent:

```
 osdteletext: can't create OSD area with requested bpp=32
```


display.c -> cDisplay32BPP::cDisplay32BPP
```
     if (osd->CanHandleAreas(Areas, sizeof(Areas) / sizeof(tArea)) != oeOk) {
         DELETENULL(osd);
+        esyslog("%s: can't create OSD area with requested bpp=%d\n", PLUGIN_NAME_I18N, bpp);
         return;
     }
```

Looks like fallback to 8-bit color should be implemented...will check how to do...

**Comment by ua0lnj** [comment]
Sttng skin + true color works fine.

**Comment by ua0lnj** [comment]
Also look at https://github.com/vdr-projects/vdr-plugin-osdteletext/issues/7

**Comment by pbiering** [comment]
osdteletext missed a fallback in case OSD is not supporting TrueColor, fixed with https://github.com/vdr-projects/vdr-plugin-osdteletext/pull/8

**Comment by pbiering** [comment]
fixed, also in case osdteletext plugin has too big size requested, an error message is dropped
